finance-tracker/config/routes.rb
Rails
  .application
  .routes
  .draw do
    root 'welcome#index'
    devise_for :users
    get 'my_portfolio', to: 'users#my_portfolio'
    get 'search_stock', to: 'stocks#search'
    resources :user_stocks, only: [:create, :destroy]
    get 'my_friends', to: 'users#my_friends'
    get 'search_friend', to: 'users#search'
    resources :users, only: [:show]
    resources :friendships, only: [:create, :destroy]
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

finance-tracker/app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

finance-tracker/app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client =
      IEX::Api::Client.new(
        publishable_token:
          Rails.application.credentials.iex_client[:sandbox_api_key],
        endpoint: 'https://sandbox.iexapis.com/v1'
      )
    begin
      new(
        ticker: ticker_symbol,
        name: client.company(ticker_symbol).company_name,
        last_price: client.price(ticker_symbol)
      )
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

finance-tracker/app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    'Anonymous'
  end

  def self.search(param)
    param.strip!
    to_send_back =
      (
        first_name_matches(param) + last_name_matches(param) +
          email_matches(param)
      ).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end
end

finance-tracker/app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

finance-tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(
      :account_update,
      keys: %i[first_name last_name]
    )
  end
end

finance-tracker/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    current_user.friendships.build(friend: User.find(params[:friend]))
    if current_user.save
      flash[:notice] = 'Following user'
    else
      flash[:alert] = 'There was something wrong with the tracking request'
    end
    redirect_to my_friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = 'Stopped following'
    redirect_to my_friends_path
  end
end

finance-tracker/app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to { |format| format.js { render partial: 'users/result' } }
      else
        respond_to do |format|
          flash.now[:alert] = 'Please enter a valid symbol to search'
          format.js { render partial: 'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter a symbol to search'
        format.js { render partial: 'users/result' }
      end
    end
  end
end

finance-tracker/app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      if stock
        stock.save
      else
        flash[:alert] = 'Please enter a valid symbol to search'
        return redirect_to my_portfolio_path
      end
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] =
      "Stock #{stock.name} was successfully added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user: current_user, stock: stock).first
    user_stock.destroy
    flash[:notice] =
      "#{stock.ticker} was successfully removed from your portfolio"
    redirect_to my_portfolio_path
  end
end

finance-tracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end
  def my_friends
    @friends = current_user.friends
  end
  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter a friend name or email to search'
        format.js { render partial: 'users/friend_result' }
      end
    end
  end
end

finance-tracker/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

finance-tracker/app/helpers/friendships_helper.rb
module FriendshipsHelper
end

finance-tracker/app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

finance-tracker/app/helpers/users_helper.rb
module UsersHelper
end

finance-tracker/app/helpers/welcome_helper.rb
module WelcomeHelper
end

finance-tracker/app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @friends %>
  <div class="card card-header results-block">
    <table class="col-md-12">
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><strong>Name: </strong> <%= friend.full_name %></td>
            <td><strong>Email: </strong> <%= friend.email %></td>
            <td>
              <strong>Actions: </strong> <%= link_to "View Profile", user_path(friend), class: "btn btn-sm btn-success" %>
              <% if current_user.not_friends_with?(friend.id) %>
                <%= link_to 'Follow friend?', friendships_path(friend: friend), class: "btn btn-sm btn-success", method: :post %>
              <% else %>
                <span class="badge badge-secondary">
                  You are friends
                </span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>


  </div>
<% end %>

finance-tracker/app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'users/friend_result.html' %>'

finance-tracker/app/views/users/_result.html.erb
<div class="results-block">
  <%= render "layouts/messages" %>
</div>

<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-xs btn-success", method: :post %>
    <% else %>
      <span class="badge badge-secondary">
        You are already tracking
        <% unless current_user.under_stock_limit? %>
          10 stocks
        <%  end %>
        <% if current_user.stock_already_tracked?(@stock.ticker) %>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

finance-tracker/app/views/users/_result.js.erb
document.querySelector("#results").innerHTML = '<%= j render 'users/result.html' %>';

finance-tracker/app/views/users/my_friends.html.erb
<h1>Friends</h1>
<div class='search-area'>
  <h3>Search Friends</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Name or email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="friend-results">

</div>
<% unless @friends.empty? %>
<%=  render 'friends/list'  %>
<% end %>

finance-tracker/app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class="search-area">
  <h3>Search Stocks</h3>
  <%= form_tag search_stock_path, method: :get, remote: true do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
        <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
</div>

<% unless @tracked_stocks.empty? %>
  <%= render "stocks/list" %>
<%  end %>

finance-tracker/app/views/users/show.html.erb
<h2>User Details</h2>


<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
    <tr>
      <td><strong>Name: </strong> <%= @user.full_name %></td>
      <td><strong>Email: </strong> <%= @user.email %></td>
      <td>
        <% if current_user.not_friends_with?(@user.id) %>
          <%= link_to 'Follow friend?', friendships_path(friend: @user),
                      class: "btn btn-sm btn-success", method: :post %>
        <% else %>
            <span class="badge badge-secondary">
              You are friends
            </span>
        <% end %>
      </td>
    </tr>
    </tbody>
  </table>
</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list'%>
<% else %>
  <p class='lead'>This user is not tracking any stocks</p>
<% end %>
<%= link_to 'Back', my_friends_path, class: "btn btn-primary" %>